### ISSUE TITLE
Generating the Data 

### ISSUE THREAD

**Issue by Jinsung-Jeon** [BorealisAI/continuous-time-flow-process#1]
First of all, thank you for your hard work.

I want to generate data from a latent vector.
That is, when aug_model(reverse=True), only augmentation is generated, but data is not generated.
I want to know how to generate data after learning data distribution using CTFP.

Thank you.

**Comment by wisdomdeng** [comment]
Hi, thanks for your interest in our paper. Could you please be more specific about what you mean by only augmentation is generated, but data is not generated?

**Comment by b53k** [comment]
@Jinsung-Jeon were you able to generate data after learning?
