### ISSUE TITLE
underflow in dt nan

### ISSUE THREAD

**Issue by naoufalEB** [BorealisAI/continuous-time-flow-process#2]
Hello,

I am having issues while running your training and testing code for the OU dataset.
The issue happens when computing the loss as I get the following error : `assert t0 + dt > t0, 'underflow in dt {}'.format(dt.item())

AssertionError: underflow in dt nan`
I found two threads ([here](https://github.com/rtqichen/torchdiffeq/issues/58) and [here](https://github.com/rtqichen/torchdiffeq/issues/57)) explaining that it is related to the **torchdiffeq** library, precisely the **dopri5** solver and the 'stiffness' of the system to solve.
I tried lowering the accuracy and using the dopri8 as recommended by the threads but it did not work.
How did you work around this issue.
Thanks a lot for your help

**Comment by wisdomdeng** [comment]
Thanks for your interest in our project. To my best memory, we did not ran into such a problem. Can you provide more details  to help you debug this issue, like the command you are running, the version of libraries you are using, and the changes to the parameters you made? Thanks!

**Comment by naoufalEB** [comment]
Hello,

Thanks for your answer. I checked once again the command and found a mistake (I didn't use the identity as activation for the OU process)
